### ISSUE TITLE
Inverted/Off Colors in noVNC

### ISSUE THREAD

**Issue by Makr91** [omniosorg/zadm#107]
Hello All,

I am not sure how zadm implements noVNC, but it would appears that when I use it on a up-date OmniOS r38 install, using a bhyve-release (ie UEFI) based image, but I am getting inverted colors on desktops. This occurs on windows, ubuntu, etc. I also get a few times that the screen becomes "blocky" when looking at just a shell console.

![image](https://user-images.githubusercontent.com/11012628/152611312-03baa359-58bb-4800-a941-cee3e0a30f10.png)

When the screen becomes blocky, refreshing the webpage briefly shows the correct screen. Desktops never become blocky, but they are always inverted.

This occurs on both Firefox and Chromium

**Comment by hadfl** [comment]
Hi @Makr91,

`zadm` just acts as a proxy (unix socket to websocket for webvnc and unix socket to TCP/IP for vnc). If you face issues they are most likely either in the VNC server (bhyve in your case) or the client.

Do you see the same breakage when you use a different VNC client?

**Comment by Makr91** [comment]
I can confirm that using a different VNC client works without issue. I will attempt to downgrade in a few hours and will report back

**Comment by Makr91** [comment]
I updated OmniOS and that fix it, thank you!
