### ISSUE TITLE
Zone naming convention issue

### ISSUE THREAD

**Issue by Makr91** [omniosorg/zadm#110]
Hello all,

I work for a MSP and we currently like to set the name of the Zone to have a prefix that we call a "partition id", just an id number for our zones to help identify location, purpose, etc. This isn't the actual hostname of the zone, but is used for situations where another zone maybe up as a clone.

When I try to modify a zone after creating it with zonecfg, I am getting the following error in zadm:

```
zadm edit "1012--web-01.dc-01.m4kr.net"
root: Execution of validator for 'limitpriv' returns with error: limitpriv not valid ()
root: Execution of validator for 'zonename' returns with error: zonename not valid (1012--web-01.dc-01.m4kr.net)
Do you want to retry [Y/n]?
```

To break down our naming convention its:

\<PARTID\>--HOSTNAME
IE: 1012--web-01.dc-01.m4kr.net

**Comment by hadfl** [comment]
Thanks for the bug report. The `zonename` validator in `zadm` is clearly a bit too restrictive. We'll fix it.
