### ISSUE TITLE
Zones Not Booting On Startup

### ISSUE THREAD

**Issue by justledbetter** [omniosorg/zadm#128]
Apologies if this is a question that's better suited for the core team, but I am not sure where the problem's coming from.

In r151042, when my systems start up, I am no longer seeing any of my zones startup, even though they have "autoboot" set to true in the zadm configuration.  `svcs -a | grep -i zone` reports:

```
online          8:05:36 svc:/system/zones-monitoring:default
offline         8:05:36 svc:/system/zones:default
```

... but I'm not sure if this is what is expected or not.  `svcadm refresh` and `svcadm enable` don't seem to make any difference to the system/zones service.

Is there somewhere else I need to configure the system to autoboot zones?

**Comment by hadfl** [comment]
as you can see from the `system/zones` service description
```
hadfl@themis:~$ svcs -l system/zones | grep ^name
name         Zones autoboot and graceful shutdown
```

it's responsible for autoboot as well as graceful shutdown. I think both your issues are related to the service not being up and running. Is there anything useful in the service logs about why it does not start (and not end up in maintenance when you try to start it but it fails).

**Comment by justledbetter** [comment]
I am not seeing anything in the  svcd logfile - is there somewhere else that errors would be logged?

```
# cat /var/svc/log/system-zones:default.log
[ May 24 08:07:51 Enabled. ]
[ May 24 08:07:55 Rereading configuration. ]
[ May 24 08:07:57 Executing start method ("/lib/svc/method/svc-zones start"). ]
[ May 24 08:07:57 Method "start" exited with status 0. ]
[ May 24 08:11:59 Enabled. ]
[ May 24 08:12:01 Executing start method ("/lib/svc/method/svc-zones start"). ]
[ May 24 08:12:01 Method "start" exited with status 0. ]
[ May 24 08:18:32 Enabled. ]
[ May 24 08:18:34 Executing start method ("/lib/svc/method/svc-zones start"). ]
[ May 24 08:18:34 Method "start" exited with status 0. ]
[ May 24 08:26:39 Enabled. ]
[ Jun  7 08:53:12 Enabled. ]
[ Jun 24 20:57:51 Enabled. ]
[ Jun 30 08:05:36 Enabled. ]
[ Jun 30 08:06:29 Rereading configuration. ]
[ Jun 30 14:38:38 Enabled. ]
```

**Comment by justledbetter** [comment]
Aha!  It seems that disabling svc:/network/inetd causes this, as it's a dependency for svc:/milestone/multi-user and multi-user-server.  This milestone is required to execute zone services?  (I had read somewhere that it was advised to disable inetd for security and didn't realize the downstream impact that would have)

**Comment by justledbetter** [comment]
Confirmed this fixed the problem.  Apologies for opening this issue up in zadm when it was clearly a case of me being dopey, but zadm is my gateway drug to all things illumos (love love love using it!) and this a lot less daunting to me than their tracker.

For future reference in case anyone else runs into the same type of problem, here's what I ran to find out what was hanging service startup:

```
$ pfexec svcs -x -v
svc:/network/inetd:default (inetd)
 State: disabled since June 30, 2022 at 09:10:57 PM EDT
Reason: Disabled by an administrator.
   See: http://illumos.org/msg/SMF-8000-05
   See: man -M /usr/share/man -s 8 inetd
   See: man -M /usr/share/man -s 8 inetadm
   See: /var/svc/log/network-inetd:default.log
Impact: 3 dependent services are not running:
        svc:/network/rpc/gss:default
        svc:/network/security/ktkt_warn:default
        svc:/network/rpc/smserver:default
```

Running `svcadm enable network/inetd` fixed everything immediately, and things started up as expected next reboot.
