### ISSUE TITLE
Schema validation error

### ISSUE THREAD

**Issue by lvlts** [omniosorg/zadm#143]
When using zadm `0.14.1` (`OmniOS r151048  omnios-r151048-24333ee74c       November 2023`), it's not possible to create a new `emu` brand zone using the instructions (default) at https://omnios.org/setup/zadm .

Command:

```
pfexec zadm create -b emu -i 41232cad arm
```

Output:

```
Mojo::File::spurt is deprecated in favor of Mojo::File::spew at /opt/ooce/zadm/lib/Zadm/Utils.pm line 201.
You did not make any changes to the default configuration,
do you want to create the zone with all defaults [Y/n]?
merging element 'cpu' : description does not match at /opt/ooce/zadm/lib/Zadm/Schema/Emu.pm line 9.
Do you want to retry [Y/n]?
```

**Comment by hadfl** [comment]
Thank you for the bug report. A fix for this issue will land soon (as well as getting rid of the deprecation warning).

As a temporary workaround I'd suggest to downgrade to 0.14.0.
