### ISSUE TITLE
`WARNING: Connect timeout` when listing images or creating lx zone

### ISSUE THREAD

**Issue by francescocarzaniga** [omniosorg/zadm#145]
When listing images or creating an lx zone, I get the following error:
`WARNING: Connect timeout`

Running `__ZADMDEBUG=1 zadm list-images` the full output is:
```
[debug] Setting effective privileges to 'basic,file_dac_read,file_dac_write,!file_link_any,file_owner,!net_access,!proc_info,!proc_session'.
[debug] /usr/bin/zonename
[debug] downloading http://download.proxmox.com/images/aplinfo.dat...
[debug] downloading https://images.smartos.org/images...
[debug] downloading https://downloads.omnios.org/media/img.json...
[debug] downloading https://downloads.omnios.org/media/img-us-west.json...
[debug] Acquiring effective privilege 'net_access'.
[debug] Releasing effective privilege 'net_access'.
[warn] WARNING: Connect timeout
UUID      PROVIDER  BRAND   NAME                                VERSION
```

**Comment by hadfl** [comment]
Are you sure this was not due to a temporary unavailability of one of the image catalogues or a network issue?

I just tried it now and it worked.

Can you please try again? If it still fails we could increase the http client timeout in `zadm`

**Comment by francescocarzaniga** [comment]
I've had this problem for the past week or so, after updating from an older version. I tried reinstalling zadm as well, but no luck.

**Comment by francescocarzaniga** [comment]
The issue was caused by a misconfiguration of IPv6. `zadm` (and `perl` in general) prefers IPv6, so it was not downloading the indices, while the rest of the system was chugging along nicely with IPv4.
