### ISSUE TITLE
Could not find a ZFS dataset for /zones/NAME [KVM branded joyent image]

### ISSUE THREAD

**Issue by stellarpower** [omniosorg/zadm#39]
Hi,

Trying to install a KVM-branded zone to try out FreeBSD. Am getting this error; following the basic walkthrough on the Omni site, I have a main dataset under `/zones` for zadm to use; I don't know if this is expected, but it has unpacked the image straight into the root pool instead of here, and is obviously complaining it can't find anything under /zones. The path seems to be hard-coded [here](https://github.com/omniosorg/zadm/blob/91f778668cd33c2bb59e06b77387e29f5c04f3ef/lib/Zadm/Zone/KVM.pm#L37), but again, I don't know if this is by design and it's my setup or if this might want looking at. 

Full session included here:

```
phoenix@phoenix:~$ zadm list-images | grep 8989
b989898c  joyent    kvm     freebsd-12                          20190424 
phoenix@phoenix:~$ pfexec zadm create -b kvm -i b989898c freebsd12_test_1
You did not make any changes to the default configuration,
do you want to create the zone with all defaults [Y/n]? y
checking image checksum...
Going to overwrite the boot disk 'rpool/freebsd12_test_1/root'
with the provided image. Do you want to continue [Y/n]? y
receiving full stream of zones/c4853a15-128c-6108-875d-fee0abc5e1ee-disk0@dataset-20190424 into rpool/freebsd12_test_1/root@dataset-20190424
  1GiB 01:00:23 [ 64.2MiB/s]
received 1.44GB stream in 38 seconds (38.9MB/sec)
ERROR: Could not find a ZFS dataset for /zones/freebsd12_test_1
phoenix@phoenix:~$ 
```

Thanks

**Comment by citrus-it** [comment]
I think there must be something unexpected about your ZFS dataset layout here, but `zadm` should definitely do some more checks and exit earlier with a better error message.

VM zones have two different paths and aspects to them, and OmniOS isolates the hypervisor inside a non-global zone.

The first is the path to the zone files, `zonepath`, which will default to `/zones/<zone name>`, although it can be customised by editing the JSON configuration file that `zadm` presents during installation. This is effectively the place that the zone root is created so that the zone can boot up and start the hypervisor.

The requirement for this is that the parent path (`/zones` by default) is a ZFS dataset, and then the system will create a child dataset under that to contain the zone. How do your datasets look around the `/zones` mountpoint?

So, for example, I have the `rpool/zones` dataset mounted on `/zones`.

```
bloody% df -h /zones
Filesystem             Size   Used  Available Capacity  Mounted on
rpool/zones          288.69G   264K     42.97G     1%    /zones
```

and when I install a zone, `rpool/zones/<zone>` is automatically created:

```
bloody# zadm install sparse
A ZFS file system has been created for this zone.

       Image: Preparing at /zones/sparse/root.
```

Separately to all of this, which applies to any zone brand, a hypervisor zone also has to have some virtual disks attached to the virtual machine. The default template that opens in an editor when you create a zone with `zadm` puts these under `rpool`, but you can edit the path (and other attributes such as size) before saving.

**Comment by stellarpower** [comment]
That's the thing, I made a quick scratch filesystem so that I could clean it off easily once I'm done having a play, now I'm on metal, but it doesn't seem to have any children, I would have assumed each zone would have its own dataset, especially for the root. But

```
phoenix@phoenix:~$ zfs list -r rpool
NAME                           USED  AVAIL  REFER  MOUNTPOINT
rpool                         26.4G  45.3G    27K  /rpool
rpool/ROOT                    2.00G  45.3G    24K  legacy
rpool/ROOT/OmniStartComplete  1.07G  45.3G   779M  /
rpool/ROOT/omnios-r151036m     120M  45.3G   720M  legacy
rpool/ROOT/omnios-r151036p     841M  45.3G  1.57G  /
rpool/dump                    1.00G  45.3G  1.00G  -
rpool/freebsd12_test_1        10.3G  45.3G    24K  /rpool/freebsd12_test_1
rpool/freebsd12_test_1/root   10.3G  55.6G    12K  -
rpool/freebsd12_test_2        11.1G  45.3G    24K  /rpool/freebsd12_test_2
rpool/freebsd12_test_2/root   11.1G  55.6G   761M  -
rpool/home                    69.5K  45.3G    24K  /home
rpool/home/phoenix            45.5K  45.3G  45.5K  /home/phoenix
rpool/swap                    1.06G  46.3G   186K  -
rpool/testing                 1002M  45.3G    24K  none
rpool/testing/zones           1002M  45.3G  1002M  /zones
rpool/zone                      24K  45.3G    24K  /zone
phoenix@phoenix:~$ ls -la /zones
total 11
drwxr-xr-x   7 root     root           7 Mar  2 03:47 .
drwxr-xr-x  24 root     root          25 Mar  2 15:15 ..
drwx------   5 root     root           5 Mar  1 23:41 arch_wayland_testing
drwx------   4 root     root           4 Mar  2 03:47 freebsd12_test_2
drwx------   5 root     root           6 Mar  2 03:56 proxmox_alpine_test_1
drwx------   5 root     root           6 Mar  1 23:09 ubuntutestzone
drwx------   5 root     root           6 Mar  2 01:47 void_wayland_testing
phoenix@phoenix:~$ 
```
That size also looks suspicious, I wouldn't have thought a BSD volume should be as large as 10-12G when Ubuntu was something like 80 meg, or is that just because of the pre-allocated space as it's a volume? I wasn't entirely sure whether this volume was the final disk image used to boot in the zone or whether this was the (expanded) template image used to create any new zones, and so, at what point it was failing. Guess I'm thinking image vs. container in docker terms.

I must admit I hadn't paid too much attention to the config file presented; I got a couple of LX zones up and running really nicely, but as things started not to boot and I was repeatedly typing out the same I just started leaving them at their default to reduce some variables.

Maybe it would also be good for zadm to take some of its global configs from a small JSON file(?) I'd probably rather keep the root pool relatively clean, and then say `zadm/images` and `zadm/installedzones` would be good places for the respective managed datasets to live.

**Comment by hadfl** [comment]
You likely hit a bug in `zoneadm(1M)`. `zadm` does not do anything special regarding the zonepath dataset but just calls `zoneadm -z <zonename> install` which creates the zone dataset and installs the zone. It seems that setting the mountpoint to `none` for the parent dataset of the zone root dataset triggers this. We'll have a look whether there is a possible fix to `zoneadm(1M)`.

`bootdisk` is the zvol which the hypervisor boots from. The volume size is set to what you specify in the config (10G in your case). If you want it to just use the space it actually consumes, set `"sparse" : "true"` in the `bootdisk` resource:
```
hadfl@nemesis:~$ zadm doc -b kvm -a bootdisk
kvm brand bootdisk attribute
    bootdisk (optional): resource containing the following attributes:

          path: path of zvol
          blocksize (optional): zvol block size
          serial (optional): serial number of disk, upper-case alpha-numeric, up to 20 characters
          size (optional): zvol disk size. according to zfs syntax
          sparse (optional): sparse zvol
```

There are a couple of "hardcoded" defaults for the default brand templates. Use `-t` and your own JSON template, which will then show up in the editor when creating a zone to override the defaults.
```
hadfl@nemesis:~$ zadm help -b kvm
...
        create -b <brand> [-i <image_uuid|image_path_or_uri>] [-t <template_path>] <zone_name>
...
```

**Comment by stellarpower** [comment]
Okay, great - when I'm back this evening or next time I can boot up I'll swap out for a new dataset and see if that fixes it, then can draw up a table and try to hone what the issue is. Zoneadm is part of illumos-gate, isn't it? Is it modified much for illumos-omnios? Also thanks regarding the doc command, hadn't seen that, and was struggling to find much via Google beyond the asciinema casts. I'm.keeping notes so maybe could spin this into a tutorial some point.

**Comment by citrus-it** [comment]
You've uncovered a bug in the illumos `zoneadm` command which apparently was reported a few years back at https://www.illumos.org/issues/2766
We'll get it fixed, thanks.

> I'm.keeping notes so maybe could spin this into a tutorial some point.

That would be excellent!

**Comment by stellarpower** [comment]
Cool, so you've got a patch. Anything else you want from me or shall I close this?
