### ISSUE TITLE
Add a `pull` Command to Download Images ahead of Zone Creation

### ISSUE THREAD

**Issue by stellarpower** [omniosorg/zadm#41]
Suggesting a pretty simple enhancement to allow downloading images ahead of zone creation, helping to speed this up later on. The verb `pull` makes sense to me and is similar to what is provided with e.g. docker; `pull-image` might also be more inline with `list-images`.

Something like:

```
phoenix@phoenix:~$ zadm list-images        
UUID      PROVIDER  BRAND   NAME                                VERSION         
3a7e89b1  joyent    illumos Brocade vTM Developer               17.4.0          
f8ad1e60  joyent    illumos apache                              14.1.0          
6a62b193  joyent    illumos apache                              14.2.0 

....

phoenix@phoenix:~$ zadm pull -b illumos -i 3a7e89b1
```
would then begin the download process, keeping the image saved for future use without necessitating creation of a zone.

**Comment by hadfl** [comment]
from version `0.7.0` on `zadm` will start the download immediately in the background while the user is busy editing the zone config. this will give a speed up. if you still think that a `pull` command would be useful, that can certainly be added.

what's the reason to also require the brand when just downloading an image matching the uuid (apart from the fact that the current image framework requires it)?

**Comment by stellarpower** [comment]
That was the reason I think, as the constructor seems to require it in order to search for the image correctly, and I initially wasn't sure if something was happening behind the scenes for KVM/bhyve after it had downloaded. If the framework will be changed and the promises can be used in parallel, perhaps altering the command to take a list of images and it could fetch them all?

```
user@host $ zadm pull 12ab35cd 78ff3ee6 99b764aa ...
```

**Comment by hadfl** [comment]
doing several image downloads in parallel would not be a big deal, the framework is already there. however printing the progress would require a bit of work. if it is ok for you i think we should make `zadm pull` just support downloading one uuid.

**Comment by stellarpower** [comment]
Sure, sounds good to me. Happy for your commit to be merged then, thanks a lot! :)
