### ISSUE TITLE
Feat. Req. - update man page with example usage

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [omniosorg/zadm#65]
It is not so clear what the options vnc and webvnc are for. If possible can some example be added? These are perfect:

"`zadm vnc` runs in the global zone and creates a bridge to the KVM or bhyve
zone's VNC server. By default it binds to the global zone's loopback interface
so you usually need to combine it with SSH tunnelling to get access from a
remote client. I usually do something like:

	ssh -n -L 8080:127.0.0.1:8080 <global zone> zadm vnc -w 8080 <zone>

Then point a web browser at http://127.0.0.1:8080/ on my local device.

To make the server bind to a specific GZ IP address, or to all
addresses, but you should take steps to prevent unauthorised access in that
case (i.e. it's probably find on a home network or if you have firewall
control on the host/network):

	zadm vnc -w 0.0.0.0:8080 <zone>

In that case, you can just point a browser at http://<gz IP>:8080/
to get VNC access."

https://illumos.topicbox.com/groups/omnios-discuss/Tbcdcd5c0c9417f52-M8f7f72cc7873941be18217bf/adding-to-the-omnios-blog-entry-setting-up-kvm-with-existing-image

**Comment by Chewbakka-Wakka** [comment]
At least a few people like the idea :)

**Comment by Makr91** [comment]
https://github.com/omniosorg/zadm/blob/master/doc/zadm.pod

you guys mean this?

**Comment by hadfl** [comment]
The man pages are generated from the POD sections in the source. However, we haven't implemented a mechanism for brand specific man pages yet. We'll gladly get it in if someone integrates it via PR.

Having said that, I don't think that mentioning e.g. that 127.0.0.1 binds to the loopback interface or how to SSH port forward is something that belongs to an application man page. If at all then rather in a walk-through or a tutorial.
